config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  devise_for :students, :controllers => {:registrations => "students/registrations"}

  root to: 'photos#index'

  get '/school', to: 'schools#example'

  resources :students, :only => [:show]
  resources :schools, :only => [:show]
  resources :dining_halls do
    resources :reviews, :only => [:show, :new, :create]
  end
  resources :photos, :only => [:index, :show]
  resources :tags, :only => [:show]



end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :school

end

app/models/diet.rb
class Diet < ActiveRecord::Base

  has_many :student_diets
  has_many :students, through: :student_diets

end

app/models/dining_hall.rb
class DiningHall < ActiveRecord::Base

  belongs_to :school
  has_many :reviews
  has_many :photos

  def average_rating
    rating_total = 0
    self.reviews.each do |review|
      rating_total += review.rating if review.rating
    end
    average = rating_total.to_f / self.reviews.length
    average.round(2)
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :review
  belongs_to :student
  belongs_to :dining_hall
  has_many :tags, as: "taggable"

  # set default ordering to created_at
  default_scope { order(created_at: :desc) }

  def self.student_homepage_photos(student_school)
    school_photos = []
    student_school.dining_halls.each do |dining_hall|
      school_photos = school_photos + dining_hall.photos.limit(10);
    end
    school_photos.shuffle
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :student
  belongs_to :dining_hall

  has_one :photo
  has_many :tags, as: "taggable"

end

app/models/school.rb
class School < ActiveRecord::Base

  has_many :students
  has_many :administrators
  has_many :dining_halls

end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  belongs_to :school
  has_many :reviews
  has_many :photos
  has_many :student_diets
  has_many :diets, through: :student_diets

end

app/models/student_diet.rb
class StudentDiet < ActiveRecord::Base

  belongs_to :student
  belongs_to :diet

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dining_halls_controller.rb
class DiningHallsController < ApplicationController

  def show
    @dining_hall = DiningHall.find(params[:id])
    @review = Review.new
    @recent_reviews = @dining_hall.reviews.order(created_at: :desc).limit(10)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_student!

  def index
    if current_student && current_student.school
      @student_school_photos = Photo.student_homepage_photos(current_student.school)
    else
      @student_school_photos = Photo.all.limit(30)
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
    @dining_hall = DiningHall.find(params[:dining_hall_id])
  end

  def create
    dining_hall = DiningHall.find(params[:dining_hall_id])
    new_review = Review.create(review_params)
    new_review.student = current_student
    new_review.dining_hall = dining_hall
    new_review.save!

    redirect_to dining_hall_review_path(dining_hall, new_review)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

def show
  @school = current_user.school
end

def example
end

end

app/controllers/students/registrations_controller.rb
class Students::RegistrationsController < Devise::RegistrationsController

  def create
    student_diets = []
    params[:diets].each do |checked_diet|
      student_diets << StudentDiet.create(:diet_id => Diet.find_by_name(checked_diet[0]).id)
    end
    student_diets.each do |student_diet|
      student_diet.student = current_student
      student_diet.save!
    end
    super
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_student!

  def home

  end

  def show
    @student = current_student
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dining_halls/show.html.erb
<%= @dining_hall.name %>
<%= @dining_hall.average_rating %>

<%= form_for([@dining_hall, @review]) do |f| %>
  Comment:<br>
  <%= f.text_area :comment %><br>
  Rating: <input id="rating" name="review[rating]" min="1" max="5" type="number" /><br>
  <%= f.submit %>
<% end %>

<% @recent_reviews.each do |review| %>
  <div>
    <% if review.photo %>
      <%= image_tag(review.photo.url)%><br>
    <% end %>
    "<%= review.comment %>"<br>
    Rating: <%= review.rating %><br>
    <%= link_to(review.student.name, student_path(review.student)) %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rumble</title>
  <script type="text/javascript" src="//use.typekit.net/pmb1dkw.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<header>
<a href="/"><%= image_tag "logo.png", class: 'logo' %></a>
</header>
<div class="overlay"></div>
<div class="container">

<%= yield %>
</div>
<div class="add-buttons">
  <ul>
    <a id="photo" href="/"><li>+PHOTO<br><i class="fa fa-2x fa-camera"></i></li></a>
    <a id="review" href="/dining_halls/<%= DiningHall.first.id %>/reviews/new"><li>+REVIEW<br><i class="fa fa-2x fa-star"></i></li></a>
    <a id="checkin" ><li>+CHECK-IN<br><i class="fa fa-2x fa-check-square"></i></li></a>
  </ul>

</div>

<div class="bottom-nav">
  <ul>
    <a href="/"><li class="border-right" > <i class="fa fa-2x fa-lightbulb-o"></i></li></a>
    <a  href="/school"><li class="border-right"> <i class="fa fa-2x fa-map-marker"></i></li></a>
    <li id="add" > <i class="fa fa-2x fa-plus"></i></li>

    <a  <% if current_student %> href="/students/<%= current_student.id %>"<% end %> ><li class="border-left"> <i class="fa fa-2x fa-user"></i></li></a>

    <a  href=""><li class="border-left" > <i class="fa fa-2x fa-heart-o"></i></li></a>

  </ul>

</div>


</body>
</html>

app/views/photos/index.html.erb
<% @student_school_photos.each do |photo| %>
  <div class="photo"><%= link_to( image_tag(photo.url, :border => 0), photo_path(photo) ) %></div>
<% end %>

app/views/photos/show.html.erb
<!-- display photo -->
<%= image_tag(@photo.url) %>
<!-- if attached to a review, show the comment and link to full review -->
<% if @photo.review %>
  <%= @photo.review.comment %>
  <%= link_to("(Full Review)", dining_hall_review_path(@photo.review.dining_hall, @photo.review))%>
<% end %>
<!-- link to student -->
<%= link_to(@photo.student.name, student_path(@photo.student)) %>
<!-- link to dining hall -->
<%= link_to(@photo.dining_hall.name, dining_hall_path(@photo.dining_hall)) %>
<% @photo.tags.each do |tag| %>
  <%= link_to(tag.name, tag_path(tag)) %>
<% end %>

app/views/reviews/new.html.erb
<%= form_for([@dining_hall, @review]) do |f| %>
<h2> <%= @dining_hall.name %></h2>
<div class="form-group">
    <select class="form-control"><option>Stir-Fry Station</option></select>
</div>
<div class="form-group">
<div class="stars">
<span>☆</span><span>☆</span><span>☆</span><span>☆</span><span>☆</span>
</div>
</div>
<div class="form-group">
  <%= f.text_area :comment, :class => 'form-control', placeholder: 'add your #twocents...' %><br>
</div>

  <!-- Rating: <input id="rating" name="review[rating]" min="1" max="5" type="number" /><br> -->
  <%= f.submit :class => 'btn btn-default' %>
  <div>
<% end %>

app/views/reviews/show.html.erb
<%= link_to(@review.dining_hall.name, dining_hall_path(@review.dining_hall)) %>
<%= @review.rating %><br>
<%= @review.comment %><br>
<%= link_to(@review.student.name, student_path(@review.student)) %>

app/views/schools/example.html.erb
<div class="full-width"><iframe width='100%' height='100%' frameBorder='0' src='https://a.tiles.mapbox.com/v3/sadler.il310lce/attribution,zoompan,zoomwheel,geocoder,share.html'></iframe>
</div>

app/views/schools/show.html.erb
<iframe width='100%' height='500px' frameBorder='0' src='https://a.tiles.mapbox.com/v3/sadler.il310lce/attribution,zoompan,zoomwheel,geocoder,share.html'></iframe>

app/views/students/show.html.erb
<div class="profile"><h3>Hi <%= @student.name %>!</h3><a href="<%= edit_student_registration_path(@student) %>"><i class="fa fa-2x fa-pencil"></i></a>

<h3>You're currently signed up as a <span class="diet-choice">kosher</span> <span class="diet-choice">vegetarian</span> with an allergy to <span class="allergy">peanuts</span>.</h3>
</div>